name: angular_quill
description: Angular dart component for the Quill rich text editor
version: 0.0.2
homepage: https://github.com/adamlofts/angular_quill
author: Adam Lofts <adam.lofts@gmail.com>

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  angular2: ^3.0.0
  func: ^1.0.0
  js: ^0.6.1
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  pageloader: ^2.2.6

dev_dependencies:
  angular_test: ^1.0.0-beta+2
  test: ^0.12.0

transformers:
- angular2:
    entry_points: example/main.dart
- angular2/transform/reflection_remover:
    $include: test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
web:
  compiler:
    debug: dartdevc
